### ISSUE TITLE
getUserMedia() で video に関する option が反映されない

### ISSUE THREAD

**Issue by kdxu** [shiguredo/react-native-webrtc-kit#3]
## 環境

- iOS 12.0
- react-native 0.57.0
- react-native-webrtc-kit 1.0.1
- xcode-select version 2349
- Xcode 10.0(Build version 10A255)
- buildTarget: iOS 10

## 状況

getUserMedia() に `RTCMediaStreamConstraints()` で渡した video に関するオプションが反映されません。
そのため、
- facingMode を `user` にしても Back Camera のまま
- アスペクト比が反映されていない
などといった問題が起こります。

**Comment by szktty** [comment]
> facingMode を user にしても Back Camera のまま

確認しました。こちらは次のリリースで修正します。

> アスペクト比が反映されていない

こちらも近日中にアスペクト比に関するオプションを増やす予定です。 VideoView の objectFit プロパティで設定可能にする予定です。リリースしたらお知らせしますので、しばらくお待ちください。

**Comment by szktty** [comment]
@kdxu facingMode を修正した 1.0.2 をリリースしました。 RTCMediaStreamConstraints によるアスペクト比の設定については次のバージョンで実装します (VideoView の設定だと勘違いしていました) 。

**Comment by kdxu** [comment]
@szktty リリース確認いたしました。対応ありがとうございます。
